name = "CheckMate"
uuid = "94fda9bc-e29e-424a-aa2b-1addfed2164c"
authors = ["Matt Helm mthelm85@gmail.com"]
version = "0.1.2"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
MacroTools = "0.5.13"
Tables = "1.12.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
